enforcer-ng/src/enforcer/enforce_cmd.c, enforcer-ng/src/enforcer/enforce_task.c, enforcer-ng/src/scheduler/schedule.c, enforcer-ng/src/scheduler/task.c
When a task is executed out of schedule and no update is
forced, no zones are iterated. Therefore the enforcer has no
return time and decides to drop the task, no more work needs
to be done.
This fixes the problem by maintaining the original task time if
nothing can be done. 'Flushed' task now sort in front of other
tasks regardless of their due time.
=> do not drop enforce task

enforcer-ng/src/enforcer/enforcer.c, enforcer-ng/src/keystate/keystate_ds.c
We must make sure the enforce task is flushed however when the ds command
is issued by the user. This fixes display of 1970 epoch dates on
ZSKs.
=> Do not set next_change to 0. This is a job of the enforcer_engine.

enforcer/src/hsmkey/hsm_key_factory.c, enforcer/src/parser/confparser.c, testing/test-cases.d/enforcer.keys.allocation/conf-mysql.xml, testing/test-cases.d/enforcer.keys.allocation/conf.xml, testing/test-cases.d/enforcer.keys.allocation/kasp.xml, testing/test-cases.d/enforcer.keys.allocation/test.sh, testing/test-cases.d/enforcer.keys.allocation/zonelist.xml
- There is a problem with logging during startup, this causes no
information regarding parsing AutomaticKeyGenerationPeriod to be outputed.
- Allow for the specification of a 0-time AutomaticKeyGenerationPeriod.
This would be normal operation in 1.4, however was changed for untrackable
reasons.
-> It is however not working to specify a period of 0, this will lead to
a situation where there are never keys generated.
-> It is in error that AutomaticKeyGenerationPeriod is a conf.xml option,
since generating keys in _per_policy_ and could very well be
differentated.
- Mark bug OPENDNSSEC-690: Shared Keys no longer working
- changed algorith length between shared and non-shared policy such that
you can differentate between keys in the hsm.
- removed wrong multiplication for the number of zones …
=> OPENDNSSEC-642, OPENDNSSEC-673, OPENDNSSEC-689, OPENDNSSEC-690: port test enforcer.keys.allocation

testing/build-opendnssec-mysql.sh, testing/test-cases.d/enforcer.timeleap.mongrel/conf-mysql.xml, testing/test-cases.d/enforcer.timeleap.mongrel/test.sh
- support for building test script under slackware distribution with …mysql
- align conf.xml and mysql version of test script
- make sure the right conf.xml is used for mysql
=> repair mongreal test

testing/test-cases-daily.d/enforcer.conf.db_hostname/test.sh
- Error message changed
The hostname of the target mysql is not available (because it is not
known that we are using the mysql driver anymore).
Note that this is a usability problem.  It makes it harder for the user
to figure out what is misconfigured.
=> OPENDNSSEC-716

testing/test-cases-daily.d/general.conf.invalid_logging/test.sh
- there is no longer a ksm util that indicates a problem, we can start the
kaspcheck and the daemons in non-daemon modus.
- the output has changed, and gotten less clear in most cases.
- enforcer will start, even though logging is not available (OPENDNSSEC-689)
=> OPENDNSSEC-710

enforcer/src/daemon/time_leap_cmd.c
Set a new value for maximum arguments
=> In 'time leap' command: show warning message when we have unknown arguments

enforcer/src/keystate/zone_del_cmd.c
renaming the signconf of deleted zone, so when creating the zone again the signer will use the new signconf file
=> OPENDNSSEC-494

testing/test-cases-daily.d/general.repository.multiple_repositories/test.sh
Skip test on ubuntu 10 due to outdated libbotan which cannot
handle multiple repositories (opened multiple times).
=> OPENDNSSEC-755 skip general.repository.multiple_repositories on ubuntu 10

signer/src/signer/zone.c
When having only ttl changes, manually setting record to null resolves the issue
=> Treat ttl chagnes like other changes

libhsm/src/bin/hsmtest.c, libhsm/src/bin/hsmtest.h, libhsm/src/bin/hsmutil.c
Without the global ctx hsmutil test <repo> would segv
=> Without the global ctx "ods-hsmutil test <repo>" would segv

signer/src/parser/signconfparser.c
MaxZoneTTL in kasp and signconf files are not mandatory
=> OPENDNSSEC-767

signer/src/signer/zone.c
Fixes OpenDNSSEC-778
backport from 2.0
=> Don't remove nsec3param but merely mark it as removed!

NEWS, signer/src/adapter/addns.c, signer/src/signer/ixfr.c
The is_initialized flag is abused to see if a ixfr has been made yet.
Now explicitely check on soamin and soaplus
=> SUPPORT-171: assert(soamin)

signer/src/adapter/addns.c, signer/src/daemon/engine.c, signer/src/signer/zone.c, signer/src/wire/notify.c
This also fixes a bug where if 2 resigns would follow up quicker than the outgoing notifies being processed the notify would wait forever (if the servers response was lost). Potentially clogging up the ixfr queue forever.
=> Open dnssec 725 waiting notify broken pipe

libhsm/src/lib/libhsm.c, libhsm/src/lib/libhsm.h, signer/src/hsm.c, signer/src/signer/keys.c, signer/src/signer/keys.h, signer/src/signer/zone.c
between re-opening HSM, perhaps even between completely logging
in again.  Therefor there is an architectural error, keys cannot
be stored stable in the zone!  This should change and we should
obtain the set of keys before starting to sign a zone, and do
away with them afterwards.  This ensures they are not used outside
of an hsm context.  This change is not feasable now.  We can
remove the HSM part of the keys effectively from the zone but we
cannot carry them around.  So for now make a cache of keys in
the hsm context.  This has major drawbacks, it is slower
and will leak memory as the HSM keys are not deallocated when
they are effectively no longer in use.  The latter will only
become severe when doing many rollbacks.
First simple implementation of the cache as a linked list.
=> OPENDNSSEC-798 improper use of key handles across hsm reopen (2.0)

enforcer/utils/ksmutil.c, signer/src/signer/zone.c
ksmutil.c:6881: warning: 'ctx' may be used uninitialized in this function
signer/zone.c:627: warning: comparison between signed and unsigned
signer/zone.c:721: warning: comparison between signed and unsigned
=> Fix build warnings spotted on OpenBSD.

configure.ac, enforcer/src/keystate/zone_add_cmd.c, signer/src/adapter/addns.c, testing/test-cases.d/enforcer.ods-enforcer.zones_and_zonelist/zonelist.xml.gold, testing/test-cases.d/enforcer.ods-enforcer.zones_and_zonelist/zonelist.xml.gold_export
for zone add command:
- checking adapter type
- the type is now case-insensitive
- if type is dns and no input/output given, the default path is used /etc/opendnsec/addns.xml as in 1.4
change ldns dependency version: 1.6.17 supports HIP record
=> OPENDNSSEC-776, OPENDNSSEC-53

signer/src/parser/signconfparser.c, signer/src/signer/backup.c, signer/src/signer/keys.c
- ignore reading rfc5011 instead of keytag
using duration format for Keyset even when the value is not set in kasp (instead of NULL)
=> incompatiblity in backup files

NEWS, signer/src/wire/axfr.c
No test created since both drill and dig refuse to give me the flags on a axfr reply.
=> OpenDNSSEC-801: set AA on AXFR reply

libhsm/src/lib/libhsm.c
The nodes of the rbtree where not freed.
=> Also free nodes in tree. This needs to go in 2.0 as well.

enforcer/src/daemon/cmdhandler.c, enforcer/src/parser/confparser.c, signer/src/daemon/cmdhandler.c, signer/src/daemon/engine.c, signer/src/ods-signer.c, signer/src/parser/confparser.c, tools/ods-control.in
Warn about long unix path used for SocketFile, but keep on using it anyway, but truncated.  This will keep on many tests still running correctly.
=> OPENDNSSEC-818: warn about long paths used for SocketFile in conf.xml

Makefile.am, conf/Makefile.am, conf/conf.xml.in, configure.ac
Introduce two new configure flags:
--enable-installation-user=<username>
--enable-installation-group=<groupname>
None, one or both options may be present.
The username and group names should be existing unix user and group names.
Configuration and data files with be installed as the desired user and/or
group.  Other files, executables and other, will be installed as the user
from which the "make install" is executed.
=> OPENDNSSEC-311: Configurable default user

signer/src/parser/zonelistparser.c
This problem is only seen while finding input adapters. Function parse_zonelist_adapter must return adapter instead of break.
=> OPENDNSSEC-828

signer/src/wire/axfr.c
missing free while iterating over IXFR parts that do not match current SOA serial
=> OPENDNSSEC-845 backport to 1.4

signer/src/wire/axfr.c
missing free while iterating over IXFR parts that do not match current SOA serial
=> OPENDNSSEC-845 backport to 2.0

signer/src/wire/axfr.c
missing free while iterating over IXFR parts that do not match current SOA serial
=> OPENDNSSEC-845

enforcer/src/scheduler/schedule.h
Fixes the following error:
```
depbase=`echo ods-enforcerd.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -std=gnu99 -DHAVE_CONFIG_H -I. -I../../common     -I../../common  -I../../common  -I./../../libhsm/src/lib  -I./../../libhsm/src/lib  -I/usr/local/include/libxml2 -I/usr/local/include  -I/usr/local/include  -I/usr/include -O2 -pipe -pedantic -Wall -pthread -fno-strict-aliasing -Wall -Wextra -Wwrite-strings -Wpointer-arith -Wno-unused-parameter -Wno-missing-field-initializers -Wformat=2 -Wcast-align -Wformat-security -Wstrict-aliasing -Wpacked -Winit-self -Wmissing-include-dirs -Wreturn-type -Wno-format-nonliteral -Wno-format-y2k -Wno-unused-function -Wno-unused-variable -Wno-sign-compare -Wno-error=unused-parameter -Wno-error=missing-field-initializers -Wno-error=format-nonliteral …
```
=> Include pthread.h to fix build error on OpenBSD.

enforcer/src/keystate/keystate_ds_submit_task.c
Warning thrown on OpenBSD:
```
keystate/keystate_ds_submit_task.c:51: warning: implicit declaration of function 'flush_enforce_task'
```
=> Fix implict declaration of flush_enforce_task.

enforcer/src/enforcer/enforcer.c
Fixes warning on OpenBSD:
```
enforcer/enforcer.c:2637: warning: 'state' may be used uninitialized in this function
```
=> Initialize 'state' to NULL.

enforcer/src/hsmkey/hsm_key_factory.c, signer/src/wire/axfr.c
Fixes build warnings on OpenBSD (where time_t is "long long"):
```
wire/axfr.c:112: warning: format '%ld' expects type 'long int', but argument 4 has type 'time_t'
wire/axfr.c:112: warning: format '%ld' expects type 'long int', but argument 5 has type 'time_t'
[...]
hsmkey/hsm_key_factory.c:195: warning: format '%lu' expects type 'long unsigned int', but argument 4 has type 'time_t'
```
=> Use "long long" for time_t.

enforcer/src/enforcer/enforcer.c, enforcer/src/hsmkey/hsm_key_factory.c, enforcer/src/keystate/key_purge.c, enforcer/src/scheduler/schedule.h, signer/src/wire/axfr.c
- Use "long long" for time_t.
- Initialize 'state' to NULL. (twice)
- Fix implict declaration of flush_enforce_task. (already changed)
- Include pthread.h to fix build error on OpenBSD.
=> OPENDNSSEC-846: Compile warnings on OpenBSD

signer/src/adapter/adapter.c, signer/src/adapter/addns.c
Do not need to change the pointer of adapter->config each time update is calling, just update its data.
xfrd->master and notify->secondary use adapter->config, so don't free this object while others use it.
=> OPENDNSSEC-838

enforcer/utils/1.4-2.0_db_convert/sqlite_convert.sql
In 1.4, the keys of deleted zones are kept in dnsseckeys while their zones don't exist any more.
In migration script we check if the zone is available, then its associated keys will be added to keyData.
=> SUPPORT-201

enforcer/src/enforcer/enforcer.c, enforcer/utils/1.4-2.0_db_convert/mysql_convert.sql, enforcer/utils/1.4-2.0_db_convert/sqlite_convert.sql
TODO: document that a completed rollover close to migration time might cause problems.
TODO: also enable this for MYSQL
=> Active keys could be omnipresent

testing/test-cases.d/general.basic.disconnectedksk/test.sh
See the commits referring to FreeBSD10 and its implmentation of
pthread_barrier_destroy.
=> The signer on FreeBSD10 in some cases may be real slow to shut down.

enforcer/src/keystate/keystate_ds.c, enforcer/src/keystate/keystate_list_cmd.c
past for key list display 'now' instead.
=> If no keys updated don't reschedule enforce for zone. If time in the

common/log.c, common/log.h, enforcer/src/daemon/verbosity_cmd.c, signer/src/daemon/cmdhandler.c, testing/test-cases.d/signer.adapters.input_basic/test.sh, testing/test-cases.d/signer.adapters.input_ixfr_notimpl/test.sh
Avoid re-opening the syslog on just changing the verbosity level, this
seem to cause either a delay or missing the change in verbosity level
alltogether.  Re-opening syslog is a bad idea anyway.
=> Change in verbosity level not (immediately) propagated to worker threads

common/scheduler/schedule.c
Previous merge issue caused task not to be taken into account when
determining when next task should fire, hence would always default
to minimum.
=> OPENDNSSEC-856: Tasks in enforcer not picked up immediately when scheduled for "now" but after a minute.

enforcer/ksm/database_access_lite.c
Warning message thrown during build:
```
database_access_lite.c:67: warning: implicit declaration of function 'select'
```
=> Fix 'select' declaration warning on OpenBSD.

NEWS, enforcer/src/daemon/cmdhandler.c, enforcer/src/ods-enforcer.c
also rephrase "Daemon exit code" to "Command exit code" as not to give
the impression the daemon has exit.
=> OPENDNSSEC-858 Don't print how long it took to execute command

signer/src/daemon/dnshandler.c, signer/src/daemon/dnshandler.h, signer/src/daemon/xfrhandler.c, signer/src/wire/netio.c, signer/src/wire/netio.h
created equally. UDP handlers must be freed individually where as TCP
handlers are all allocated in one big block.
=> Finally wrapped head around handlers. Turns out not all handlers are

enforcer/src/enforcer/update_all_cmd.c, enforcer/src/enforcer/update_conf_cmd.c, enforcer/src/ods-enforcerd.c, enforcer/src/ods-migrate.c, signer/src/daemon/engine.c, signer/src/ods-signerd.c
Doing otherwise by default triggers an assertion in the NetBSD/7.0 pthread library,
and therefore results in a core dump.
=> Don't call xmlCleanupThreads() directly, because xmlCleanupParser() has already done so.

signer/src/signer/zone.c, testing/test-cases-daily.d/enforcer.ods-enforcer.key_functions/test.sh
do not need to change rr in config if the status isn't changed
test: by default key export doesn't show any sha1
=> zone and cofig need their own copy of rr for nsec3params

NEWS, enforcer/src/keystate/zone_add_cmd.c
OPENDNSSEC-879 --suspend option wasn't working since 2.1 due individual scheduling of zones.
=> OPENDNSSEC-879 --suspend option wasn't working since 2.1

NEWS, enforcer/enforcerd/enforcer.c, enforcer/ksm/ksm_key.c
way which is mostly but not entirely correct. Which in some cases (when
the KSK and ZSK have exactly the same parameters) causes a problem for
generating KSKs. Paired with a slightly incorrect database (extraneous
keys for a policy, caused by changing policies for zones) would have the
enforcer conclude there are in fact enough keys available.
=> OPENDNSSEC-752: The 1.4 enforcer calculates the keys it requires in a

NEWS, signer/src/adapter/adapi.c, signer/src/signer/rrset.c, signer/src/signer/rrset.h, signer/src/signer/zone.c
Same as other 890 but PR against 2.1/develop
=> OPENDNSSEC-890: bogus sigs on mismatching TTLs

conf/conf.rnc, conf/conf.xml.in, enforcer/src/parser/confparser.c, libhsm/checks/confparser.c, libhsm/src/bin/confparser.c, libhsm/src/lib/libhsm.c, libhsm/src/lib/libhsm.h, signer/src/parser/confparser.c
Forward port AllowExtraction option that was missing in 2.1 from late
development in 1.4.
In addition the public key configuration option wasn't passed properly.
This passing is still quite ugly, but at least now consistent.
=> OPENDNSSEC-906 forward port of AllowExtract (2.1)

enforcer/src/enforcer/enforcer.c
The 32 and 64 bit machines sometimes get different results for this comparison
Let's cast time_t to unsigned int to have the same type, also always set time when the value is not already set.
=> OPENDNSSEC-886: Improper time calculation on 32 bits machine causes purge time to be skipped

conf/conf.rnc, conf/conf.xml.in, enforcer/src/parser/confparser.c, libhsm/checks/confparser.c, libhsm/src/bin/confparser.c, libhsm/src/lib/libhsm.c, libhsm/src/lib/libhsm.h, signer/src/parser/confparser.c
Forward port AllowExtraction option that was missing in 2.1 from late
development in 1.4.
In addition the public key configuration option wasn't passed properly.
This passing is still quite ugly, but at least now consistent.
=> OPENDNSSEC-906 forward port of AllowExtract

NEWS, signer/src/adapter/adapi.c, signer/src/signer/rrset.c, signer/src/signer/zone.c, testing/test-cases.d/signer.zones.validate_many_zones/test.sh
OPENDNSSEC-908: Capping to MaxZoneTTL breaks IXFR
=> OPENDNSSEC-890: Set TTLs or RRs to ORIG TTL in signature.

enforcer/src/db/test/Makefile.am, signer/src/Makefile.am, signer/src/adapter/adapi.c, signer/src/daemon/engine.c, signer/src/daemon/signertasks.c, signer/src/signer/backup.c, signer/src/signer/zone.c, signer/src/signer/zone.h, signer/src/test/Makefile.am, signer/src/views/recordset.c
- added missing files from distribution related to unit testing in dist
- disabled non-functional unit testing of enforcer
- Partial support for reading old-style backup files
- will read the contents and signatures
- will not preserve the signatures yet, because they immediately expire
- will not preserve NSEC chain and will be rebuild
in effect most will will be redone, but is a step towards reusing backup files
=> Partial work on migration form previous backup files.

common/utilities.c, common/utilities.h, signer/src/daemon/signeroperation.c, signer/src/test/signertest.c, signer/src/views/commitlog.c, signer/src/views/httpd.c, signer/src/views/index.c, signer/src/views/iteratorgeneric.c, signer/src/views/marshalling.c, signer/src/views/recordset.c, signer/src/views/table.c, signer/src/views/views.c, signer/src/views/zoneinput.c, signer/src/views/zoneoutput.c
Compilation problems under Ubuntu because header files have macros which cannot handle optimization being turned off after the header file has been loaded.
=> Compilation problems under Ubuntu

Doxyfile.in
This makes the various paths relative to the project root directory
instead of being absolute.
=> Strip the build directory from the doxygen docs

tools/ods-kasp2html.in
This script is invoked as /bin/sh but it uses the substitution shell
parameter expansion which is specific to bash and doesn't work in
POSIX sh.
=> remove bashisms from ods-kasp2html.in

enforcer/man/ods-enforcer.8.in
The ".R" sequence is invalid in a man page.
=> Fix the ods-enforcer man page

testing/test-cases.d/signer.support_229/conf-mysql.xml, testing/test-cases.d/signer.support_229/conf.xml, testing/test-cases.d/signer.support_229/kasp.xml, testing/test-cases.d/signer.support_229/test result observations.txt, testing/test-cases.d/signer.support_229/test.sh, testing/test-cases.d/signer.support_229/unsigned/example.com, testing/test-cases.d/signer.support_229/zonelist.xml
The test currently fails for the same reason as SUPPORT-229, namely that the zone ends up broken because the RRSIGs were created by a ZSK which ceases to exist thus orphaning the RRSIGs meaning that they cannot be verified.
=> Added a regression test case which attempts to reproduce SUPPORT-229.

enforcer/src/db/dbw.h, enforcer/src/db/key_data.c, enforcer/src/db/key_data.h, enforcer/src/enforcer/enforcer.c, enforcer/src/keystate/keystate_ds_gone_cmd.c
Add new state to ds_at_parent: DBW_DS_AT_PARENT_GONE. Now we can detect ds-gone key from unsubmitted one by looking at ds_at_parent
=> Alternative patch for rollover issue

conf/conf.rnc, conf/conf.rng
A trivial naming mistake in the conf/conf.rn[cg] files breaks the
AllowExtraction configuration option. Patch upstreamed from Debian,
bug #928021.
=> conf/conf.rn*: fix AllowExtraction

NEWS, common/scheduler/task.c, enforcer/src/keystate/keystate_list_cmd.c, enforcer/src/ods-migrate.c, enforcer/src/parser/confparser.c, enforcer/utils/1.4-2.0_db_convert/convert_mysql, signer/src/signer/rrset.c, signer/src/wire/edns.c, version.m4
SUPPORT-245, SUPPORT-244:
Resolve memory leak in signer since 2.1.4.
Don't require Host and Port to be specified in conf.xml   when migrating with a MySQL-based enforcer database backend.
Allow for MySQL database to be pre-generated when running the migration.
Full list of key states, that combined the -d and -v without trying to  be backwards compatible.
=> Memory leak

enforcer/man/ods-enforcer.8.in, enforcer/src/Makefile.am, enforcer/src/daemon/enforcercommands.c, enforcer/src/keystate/zone_set_policy_cmd.c, enforcer/src/keystate/zone_set_policy_cmd.h
Introduced a new command for setting the policy of a zone. I thought it was too cumbersome, error-prone and probably racy as well to do it through a zonelist export, edit, zonelist import sequence, and also I got the feeling that the general direction is moving towards not using zonelist.xml at all (the user-visible one).
Please let me know what you think and whether it meets your requirements. I was thinking also of using "change-policy" instead of "set-policy", but I'll let you decide on which is better.
=> Feature: Add `ods-enforcer zone set-policy` command

common/clientpipe.c, common/cmdhandler.c
Some targets have memory alignment requirements, for instance ARM and MIPS. There, unaligned memory accesses can raise CPU exceptions and kill the process. Doing memcpy's is less pretty but more robust.
=> Do memcpy instead of casts not to break alignment

common/log.c
`log_ident` was unnecessarily initialized for syslog logging, and was `NULL` when file or stderr logging was in use, resulting in "null" strings in logfile/console.
=> Fix log_ident to be initialized only for file/console logging

enforcer/src/ods-migrate.c
On Fedora/RHEL/CentOS, the unversioned .so files are in the -devel
packages, which should not be needed for normal usage of a package. For
now, try to find libsqlite3.so.0 first, as that seems to be the current
(and only) released versioned .so file for libsqlite.
Issue found by Alexander Bokovoy <abokovoy@redhat.com>
=> Do not depend on unversioned libsqlite3.so file

enforcer/src/db/hsm_key.h, enforcer/src/db/key_data.h, enforcer/src/enforcer/enforcer.c, enforcer/src/keystate/keystate_export_cmd.c, enforcer/src/keystate/keystate_import_cmd.c, enforcer/src/ods-migrate.c, libhsm/src/lib/libhsm.c, libhsm/src/lib/libhsmdns.h
Fix key export for [SUPPORT-253](https://issues.opendnssec.org/browse/SUPPORT-253) by using the correct key flags.
Fix other key operations that use the wrong key flag for CSKs.
=> SUPPORT-253: Use correct key tag for CSK

enforcer/src/keystate/keystate_export_cmd.c
This is required because the key tag is not a unique identifier and it is difficult to identify CSKs by key state because it's frequently "mixed".
=> SUPPORT-257: Allow exporting keys by CKA_ID
