- enforcer-ng/src/scheduler/schedule.c
- libhsm/src/lib/libhsm.c
- signer/src/adapter/addns.c
- signer/src/daemon/dnshandler.c
> Static analyse

- enforcer-ng/src/daemon/time_leap_cmd.c
- enforcer-ng/src/enforcer/enforce_cmd.c
- enforcer-ng/src/enforcer/enforce_task.c
- enforcer-ng/src/policy/policy_import.c
> compiler warnings

- enforcer/ksm/include/ksm/ksmutil.h
- enforcer/utils/ksmutil.c
- testing/test-cases.d/enforcer.keys.rollovers_many_timeshift_rfc5011/test.sh
> Revoke command line

- testing/functions-opendnssec.sh
- testing/test-cases.d/enforcer.rollover.manual_rollover/kasp.xml
- testing/test-cases.d/enforcer.rollover.manual_rollover/test.sh
- ods_timeleap_seach_key function is jumping to the time that a specific key is available
- ods_timeleap_search_nokey function is jumping to the time that a specific key is gone
> adding timeleap commands to the test case

- testing/functions-opendnssec.sh
- testing/test-cases.d/enforcer.keys.allocation/test.sh
- testing/test-cases.d/signer.zones.validate_many_zones/test.sh
Experimental, it seems the sleep makes the build more stable?
> Stabelize trunk build on jenkins

- enforcer/src/enforcer/enforcer.c
- enforcer/src/keystate/keystate_ds.c
> key_data_t is being overwritten overy time next is called.

- enforcer/src/daemon/cfg.c
- enforcer/src/ods-enforcerd.c
> config file on commandline

- testing/test-cases-daily.d/enforcer.conf.dssubmit_good_ckaid/test.sh
- testing/test-cases-daily.d/enforcer.conf.dssubmit_nofile/test.sh
- testing/test-cases-daily.d/enforcer.conf.dssubmit_nonexec/test.sh
- testing/test-cases-daily.d/enforcer.ods-enforcer.algo_change/test.sh
- testing/test-cases-daily.d/enforcer.rollover.dsseen_bad/test.sh
- testing/test-cases-daily.d/signer.adaptors.bind_stress_test/test.sh
-reduce sleeping time to 5 by using leap_over function
-remove waitfor_key function, the reset_env calls this func
-stopping enforcer before returning
> daily test cases

- .gitignore
- disable test which fails under mysql, even after repairing test
and configuration file.
> OPENDNSSEC-713

- testing/test-cases-daily.d/enforcer.conf.move_kasp_db/test.sh
> Fix test enforcer.conf.move_kasp_db

- MIGRATION
- enforcer/ksm/include/ksm/database.h
- enforcer/utils/database_create.mysql
- enforcer/utils/database_create.sqlite3
- enforcer/utils/migrate_1_4_8.mysql
- enforcer/utils/migrate_1_4_8.sqlite3
#build test because 1 line of code changed.
> database schema has changed. Provide migration scripts

- enforcer/src/enforcer/enforcer.c
- enforcer/src/keystate/rollover_list_cmd.c
this function can not fail.
I decided not to add a info string on rollover list since it does in fact indicate the next rollover (i.e. not the next transition)
> next_roll was never properly set. Also, given proper input

- enforcer/src/enforcer/enforce_task.c
- enforcer/src/enforcer/enforce_task.h
- enforcer/src/enforcer/enforcer.c
- enforcer/src/hsmkey/hsm_key_factory.c
- enforcer/src/hsmkey/hsm_key_factory.h
- enforcer/src/keystate/keystate_ds_seen_cmd.c
- enforcer/src/ods-enforcer.c
- testing/test-cases.d/enforcer.rollover.manual_rollover/test.sh
- testing/test-cases.d/general.basic.sign_added_deleted_zones/test.sh
Fixes failure of DS to go to omnipresent
> Ds seen unexpected state

- testing/test-cases-daily.d/enforcer.ods-enforcer.policy_purge/test.sh
Using idle command before purging policy
> fix daily test enforcer.ods-enforcer.policy_purge

- enforcer/src/hsmkey/backup_hsmkeys_cmd.c
- enforcer/src/keystate/keystate_export_cmd.c
- enforcer/src/scheduler/schedule.c
- enforcer/src/scheduler/task.c
- enforcer/src/signconf/signconf.c
- signer/src/scheduler/schedule.c
- drop some unused functions
- make some locally used functions static
> drop some dead code

- enforcer/src/keystate/zone_add_cmd.c
- enforcer/src/keystate/zonelist_import.c
Show warning message when introducing zone without unsigned file
> OPENDNSSEC-680

- .gitignore
- common/file.c
- common/str.c
- enforcer/src/daemon/cmdhandler.c
- enforcer/src/daemon/cmdhandler.h
- enforcer/src/enforcer/enforce_task.c
- enforcer/src/enforcer/enforcer.c
- enforcer/src/hsmkey/hsm_key_factory.c
- enforcer/src/keystate/keystate_list_cmd.c
- enforcer/src/keystate/rollover_list_cmd.c
- enforcer/src/keystate/zonelist_import.c
- enforcer/src/parser/confparser.c
- enforcer/src/policy/policy_import.c
- enforcer/src/policy/policy_resalt_task.c
- enforcer/src/scheduler/task.c
- enforcer/src/signconf/signconf.c
- enforcer/src/utils/kc_helper.c
- libhsm/src/lib/libhsm.c
- signer/src/wire/netio.c
- testing/test-cases.d/enforcer.keys.generate/test.sh
- testing/test-cases.d/enforcer.keys.rollovers_many_timeleap/kasp.xml
- testing/test-cases.d/enforcer.timeleap.mongrel/test.sh
This reverts commit f2854c2e21477612d753634d04bcdcef2fd9f743, reversing
changes made to 1556159b427efbba2f3ea8b68a0bfa465cf73348.
> Revert "Merge pull request #299 from yschaeff/cleanup"

- enforcer/src/keystate/keystate_rollover_cmd.c
- testing/test-cases.d/enforcer.rollover.manual_rollover/test.sh
implementing 'rollover --policy [--keytype]'
> OPENDNSSEC-596

- enforcer/src/enforcer/repositorylist_cmd.c
- testing/test-cases.d/enforcer.keys.shared/test.sh
> - Let slow machine more time to move to the next state

- KNOWN_ISSUES
- enforcer/src/policy/policy_resalt_task.c
- testing/test-cases.d/enforcer.keys.generate/test.sh
- testing/test-cases.d/enforcer.keys.rollovers_many_timeleap/kasp.xml
due to rescheduling of resalt number of keys change
> resalt never rescheduled

- NEWS
- signer/src/wire/query.c
> fixup confusion which SOA serial is on disk

- signer/src/adapter/addns.c
- signer/src/wire/query.c
- signer/src/wire/xfrd.h
hop back and forth between code paths.
> Make handling of notifies more consistent. Previous implementation would

- signer/src/adapter/addns.c
- signer/src/daemon/engine.c
- signer/src/daemon/xfrhandler.c
- signer/src/daemon/xfrhandler.h
- signer/src/wire/query.c
- signer/src/wire/xfrd.c
- signer/src/wire/xfrd.h
> Tcp waiting queue2

- KNOWN_ISSUES
- signer/src/adapter/addns.c
- signer/src/daemon/engine.c
- signer/src/daemon/xfrhandler.c
- signer/src/daemon/xfrhandler.h
- signer/src/wire/query.c
- signer/src/wire/xfrd.c
- signer/src/wire/xfrd.h
> Tcp queue fix 147

- signer/src/adapter/addns.c
- signer/src/daemon/engine.c
- signer/src/daemon/xfrhandler.c
- signer/src/daemon/xfrhandler.h
- signer/src/wire/query.c
- signer/src/wire/xfrd.c
- signer/src/wire/xfrd.h
Cherrypick changes from 1.4/develop
> Tcp waiting queue develop

- NEWS
- version.m4
> 1.4.9 release

- testing/test-cases-daily.d/enforcer.conf.db_hostname/conf-correct.xml
- testing/test-cases-daily.d/enforcer.conf.db_hostname/conf.xml
- testing/test-cases-daily.d/general.repository.pin_incorrect_01/test.sh
- testing/test-cases-daily.d/general.repository.pin_incorrect_02/test.sh
after this commit '55ea961', engine_setup doesn't access to hsm becuase it is not opened, so searching for another message
> Fix failed test

- plugins/ods-sequencer
tool that creates a sequence of signconf configurations.
> Tool that creates a sequence of signconf configurations.

- signer/src/signer/zone.c
> Don't remove nsec3param but merely mark it as removed!

- NEWS
- enforcer/src/ods-enforcer-db-setup.c
- libhsm/src/bin/hsmutil.c
> OpenDNSSEC-99: add --force flag to ods-enforcer-db-setup

- signer/src/signer/zone.c
- version.m4
Simple backport that cleanly applies.  Also prepare for release by making sure version number is set correctly.
> Backport of pull request  #408

- signer/src/signer/zone.c
> OpenDNSSEC-807 For NSEC3PARAM records, don't complain (loudly) when

- testing/test-cases.d/enforcer.policy.ttl_change/conf-mysql.xml
- testing/test-cases.d/enforcer.policy.ttl_change/conf.xml
- testing/test-cases.d/enforcer.policy.ttl_change/kasp-short-ttl.xml
- testing/test-cases.d/enforcer.policy.ttl_change/kasp.xml
- testing/test-cases.d/enforcer.policy.ttl_change/test.sh
- testing/test-cases.d/enforcer.policy.ttl_change/zonelist.xml
rollover time of the current published key. (it should not!)
> Add test to see if a decrease in TTL of a policy would influence the

- configure.ac
- signer/src/signer/backup.c
- testing/test-cases.d/signer.adapters.input_basic/test.sh
- The error occurs when upgrading to 1.4.8 or later versions due to adding rfc5011
change ldns dependency version to 1.6.17 due to supporting HIP record
> fix corrupted backup files

- enforcer/src/daemon/time_leap_cmd.c
- enforcer/src/keystate/keystate_ds_submit_task.c
- testing/test-cases.d/enforcer.policy.ttl_change/conf.xml
- testing/test-cases.d/enforcer.policy.ttl_change/kasp.xml
- testing/test-cases.d/enforcer.policy.ttl_change/test.sh
Next to the test, also the avoidance to leap back in time is included.
> OPENDNSSEC-756: repair ttl change test.

- ANNOUNCE
- configure.ac
- enforcer/man/Makefile.am
- enforcer/man/ods-enforcer-db-setup.8.in
- version.m4
Also prepare version number for release.
re-add announcement file.
> Add manual page for ods-enforcer set-up.

- libhsm/src/lib/libhsm.c
- libhsm/src/lib/libhsm.h
- signer/src/adapter/adapi.c
- signer/src/daemon/cmdhandler.c
- signer/src/signer/backup.c
- signer/src/signer/domain.c
- signer/src/signer/ixfr.c
- signer/src/signer/ixfr.h
- signer/src/signer/namedb.c
- signer/src/signer/rrset.c
- signer/src/signer/tools.c
- signer/src/signer/zone.c
- signer/src/wire/netio.c
- signer/src/wire/netio.h
> Hunting leaks bisect2

- signer/src/signer/backup.c
ODS2. has extra field keyset compare to 1.4.
> ODS2. has to read 1.4 backup file successfully.

- enforcer/src/scheduler/schedule.c
The reason we allow recursive locks is because we broadcast
a condition in an ISR. The main thread would receive this
interrupt. If we would do no locking in the ISR we risk missing
conditions. If we use a normal mutex we risk a deadlock if the
main thread occasionally grabs the lock.
> Make schedule lock recursive

- enforcer/src/keystate/keystate_export_cmd.c
- enforcer/src/keystate/keystate_list_cmd.c
Improve filtering, help and whitespace for 'key export' command
remove DEAD state which is not valid in 2.X
> OPENDNSSEC-833

- NEWS
- enforcer/src/enforcer/enforcer.c
- enforcer/utils/1.4-2.0_db_convert/mysql_convert.sql
- enforcer/utils/1.4-2.0_db_convert/sqlite_convert.sql
- testing/test-cases-daily.d/enforcer.ods-enforcer.policy_purge/kasp.xml
- testing/test-cases-daily.d/enforcer.ods-enforcer.policy_purge/kasp_3policies.xml
- testing/test-cases-daily.d/enforcer.signconf.nsec3ttl/goldA/no-ttl.xml
- testing/test-cases-daily.d/enforcer.signconf.nsec3ttl/goldA/with-0-ttl.xml
- testing/test-cases-daily.d/enforcer.signconf.nsec3ttl/goldA/with-ttl.xml
- testing/test-cases-daily.d/enforcer.signconf.nsec3ttl/goldB/no-ttl.xml
- testing/test-cases-daily.d/enforcer.signconf.nsec3ttl/goldB/with-0-ttl.xml
- testing/test-cases-daily.d/enforcer.signconf.nsec3ttl/goldB/with-ttl.xml
- testing/test-cases-daily.d/enforcer.signconf.nsec3ttl/kasp.reversed.xml
- testing/test-cases-daily.d/enforcer.signconf.nsec3ttl/kasp.xml
- testing/test-cases-daily.d/enforcer.signconf.nsec3ttl/kasp.xml.gold_exported
- testing/test-cases-daily.d/enforcer.signconf.nsec3ttl/kasp.xml.gold_exported2
- testing/test-cases-daily.d/enforcer.signconf.nsec3ttl/test.sh
Most of the things required for the 202 release.
> Prep release

- NEWS
- signer/src/signer/ixfr.c
> soamin and soaplus are now always references to min and plus. So

- NEWS
- signer/src/signer/rrset.c
> Somehow the NSEC3PARAM rr is marked added. And somehow this affects

- common/janitor.c
- signer/src/scheduler/schedule.c
@yschaeff I took your changes from your naughty branch and added on them.
> Misc fixes

- NEWS
- signer/src/wire/xfrd.c
> OPENDNSSEC-853 serial_xfr_acquired not updated in state file

- NEWS
- enforcer/src/enforcer/enforcer.c
- m4/acx_ssl.m4
- signer/src/wire/tsig-openssl.c
- version.m4
Now based on the correct branch.
> Infinite key dependencies devel

- NEWS
- enforcer/utils/convert_database.pl
Only two fields where added to the dnsseckeys table
> Update mysql<->sqlite migration script for next database version.

- common/janitor.c
Wierd thing happen. Just let if leak for now. Only once per thread.
> just leak it for now

- libhsm/checks/Makefile.am
- libhsm/checks/softhsm.conf
- libhsm/checks/softhsm2.conf
- m4/acx_pkcs11_modules.m4
- prepdist.sh
- signer/README
- testing/build-opendnssec-mysql.sh
- testing/build-opendnssec.sh
- testing/functions-opendnssec.sh
- testing/lib.sh
- testing/make.sh
- testing/test-cases-daily.d/general.repository.module_wrong/conf-mysql-no-module.xml
- testing/test-cases-daily.d/general.repository.module_wrong/conf-no-module.xml
- testing/test-cases-daily.d/general.repository.module_wrong/test.sh
- testing/test-cases-daily.d/general.repository.multiple_repositories/softhsm.conf
- testing/test-cases-daily.d/general.repository.multiple_repositories/softhsm2.conf
- testing/test-cases-daily.d/general.repository.multiple_repositories/test.sh
- testing/test-cases-daily.d/general.repository.token_1_char/softhsm.conf
- testing/test-cases-daily.d/general.repository.token_1_char/softhsm2.conf
- testing/test-cases-daily.d/general.repository.token_many_chars/softhsm.conf
- testing/test-cases-daily.d/general.repository.token_many_chars/softhsm2.conf
- testing/test-cases.d/general.basic.disconnectedksk/softhsm2.conf
- testing/test-cases.d/general.basic.disconnectedksk/test.sh
- testing/test-cases.d/signer.adapters.bind_stress_test/test.sh
- testing/test-daily-opendnssec.sh
- tools/solaris/ods-enforcerd.init.in
- tools/solaris/ods-signerd.init.in
- drop unused functions searching for C++ compiler for running tests
- improve the parameter substitution for running tests
> OPENDNSSEC-721 SoftHSMv2

- ANNOUNCE
- MIGRATION
- version.m4
Add annoucement file, migration and update version for release
candidate.
> OPENDNSSEC-802 prepare for 2.1.0 release candidate 1

- enforcer/src/ods-migrate.c
- testing/build-opendnssec.sh
- testing/make.sh
- testing/test-cases-daily.d/general.repository.multiple_repositories/test.sh
- testing/test-cases-daily.d/general.repository.token_1_char/test.sh
- testing/test-cases-daily.d/general.repository.token_many_chars/test.sh
- testing/test-daily-opendnssec-mysql.sh
- drop uncommented compile of libbotan
- repair unit tests that thought slot 1 would be available before
intiailign slot 0.
> repair some daily tests

- .gitignore
Reverts opendnssec/opendnssec#678
> Revert "OPENDNSSEC-890: correct mismatch TTLs"

- enforcer/src/keystate/zonelist_import.c
zones.xml must be updated when running zonelist import --remove-missing-zones
> OPENDNSSEC-897

- NEWS
- enforcer/src/enforcer/autostart_cmd.c
- enforcer/src/hsmkey/hsm_key_factory.c
- enforcer/src/keystate/zone_add_cmd.c
- enforcer/src/keystate/zonelist_import.c
- enforcer/src/policy/policy_import.c
ManualKeyGeneration is configured.
OPENDNSSEC-901
> Don't automatically schedule key generation task when

- NEWS
> update news explicit ordering.

- signer/src/daemon/signertasks.c
- signer/src/signer/backup.c
- signer/src/signer/zone.c
- signer/src/signer/zone.h
- signer/src/test/signertest.c
- signer/src/test/unsigned.zone.example.backup2
- signer/src/views/commitlog.c
- signer/src/views/proto.h
- signer/src/views/recordset.c
- signer/src/views/views.c
now properly creates nsec chain and records expiry time.
> make reading backup files 2.1 functional

- signer/src/daemon/signercommands.c
- Add time leap debugging functionality for the signer the same
way as the enforcer.
> OPENDNSSEC-942-2.1: Time leap debug command for signer.

- signer/src/daemon/signercommands.c
- Add time leap debugging functionality for the signer the same
way as the enforcer.
> OPENDNSSEC-942-2.2: Time leap debug command for signer.

- enforcer/src/keystate/zone_add_cmd.c
I believe it should be called in this location; please verify.
> Add missing dbw_free() call

- signer/man/ods-signer.8.in
- signer/man/ods-signerd.8.in
The man pages should be in section 8 (system administration tools),
not 22.
> Fix the ods-signer and ods-signerd man pages

- testing/build-opendnssec-mysql.sh
- testing/build-opendnssec.sh
- testing/lib.sh
> Add DISTRIBUTION=devuan support

- NEWS
- common/clientpipe.h
- common/file.h
- enforcer/src/daemon/verbosity_cmd.c
- enforcer/src/keystate/keystate_ds.c
- enforcer/src/utils/kc_helper.h
- libhsm/src/lib/libhsm.h
- signer/src/daemon/signercommands.c
From original PR#747, but conflicts needed to be merged.
> Correct some printf format messages and add printf format style checking if available for them.

- NEWS
- common/clientpipe.h
- common/confparser.c
- common/file.h
- common/scheduler/task.c
- enforcer/man/ods-enforcer.8.in
- enforcer/src/daemon/engine.c
- enforcer/src/daemon/verbosity_cmd.c
- enforcer/src/keystate/keystate_ds.c
- enforcer/src/keystate/keystate_list_cmd.c
- enforcer/src/utils/kc_helper.h
- libhsm/src/lib/libhsm.h
- signer/src/daemon/signercommands.c
- signer/src/daemon/signeroperation.c
- signer/src/wire/edns.c
Forward port changes from past week where relevant.
> Incorporate recent changes ffrom 2.1/develop

- enforcer/src/keystate/keystate_export_cmd.c
This is required because the key tag is not a unique identifier and it is difficult to identify CSKs by key state because it's frequently "mixed".
> SUPPORT-257: Allow exporting keys by CKA_ID
